security:
    encoders:
        App\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        db_users:
            entity: { class: App\Entity\User, property: email }

    firewalls:
        main:
            anonymous: ~